blue_media_task_item:
    resource: "@BlueMediaTaskBundle/Resources/config/routing/item.yml"
    prefix:   /item/

blue_media_task_homepage:
    path:     /
    defaults: { _controller: BlueMediaTaskBundle:Default:index }



