item:
    path:     /
    defaults: { _controller: "BlueMediaTaskBundle:Item:getItems" }
    methods: [GET]

item_show:
    path:     /{id}/
    defaults: { _controller: "BlueMediaTaskBundle:Item:getItem" }
    methods: [GET]

item_update:
    path:     /{id}/
    defaults: { _controller: "BlueMediaTaskBundle:Item:updateItem" }
    methods: [PUT]

item_new:
    path:     /
    defaults: { _controller: "BlueMediaTaskBundle:Item:createItem" }
    methods: [PUT]

item_delete:
    path:     /{id}/
    defaults: { _controller: "BlueMediaTaskBundle:Item:deleteItem" }
    methods: [DELETE]